<div class="page-header">
    <div class="row">
        <h1 class="col-sm-4 text-center text-left-sm col-xs-12">
            <i class="fa fa-calendar page-header-icon"></i>&nbsp;&nbsp;<a href="<?= $this->url('timesheet-work-days');?>">Timesheet</a>
        </h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <!-- col-lg-4 start here -->
        <div class="panel panel-default plain">
            <!-- Start .panel -->
            <div class="panel-heading">
                <h4 class="panel-title">2014 February</h4>
            </div>
            <div class="panel-body">
                <table class="table table-hover table-bordered">
                    <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <?php for($i=1; $i<32; $i++): ?>
                            <?php if (in_array($i, [7, 8])): ?>
                                <th class="active text-center"><?= sprintf("%'.02d", $i); ?></th>
                            <?php else: ?>
                                <th><?= sprintf("%'.02d", $i); ?></th>
                            <?php endif; ?>
                        <?php endfor; ?>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Mark Поликарпов</td>
                        <?php for($i=1; $i<32; $i++): ?>
                            <?php if (in_array($i, [7, 8])): ?>
                                <td class="active text-center">&nbsp;</td>
                            <?php elseif (in_array($i, [9])): ?>
                                <td class="active text-center"><i class="fa fa-star-o"></i></td>
                            <?php else: ?>
                                <td>&nbsp;</td>
                            <?php endif; ?>
                        <?php endfor; ?>
                    </tr>
                    <tr>
                        <td>Jacob Гултурян</td>
                        <?php for($i=1; $i<32; $i++): ?>
                            <?php if (in_array($i, [3, 5, 12, 16])): ?>
                                <td class="warning text-center">Б</td>
                            <?php elseif (in_array($i, [4, 10, 21])): ?>
                                <td class="danger text-center">П</td>
                            <?php elseif (in_array($i, [6, 13, 26])): ?>
                                <td class="info text-center">О</td>
                            <?php elseif (in_array($i, [2, 15, 27])): ?>
                                <td class="success text-center">У</td>
                            <?php elseif (in_array($i, [7, 8])): ?>
                                <td class="active text-center">&nbsp;</td>
                            <?php elseif (in_array($i, [9])): ?>
                                <td class="active text-center"><i class="fa fa-star-o"></i></td>
                            <?php else: ?>
                                <td>&nbsp;</td>
                            <?php endif; ?>
                        <?php endfor; ?>
                    </tr>
                    <tr>
                        <td>Larry Москаленко</td>
                        <?php for($i=1; $i<32; $i++): ?>
                            <?php if (in_array($i, [7, 8])): ?>
                                <td class="active text-center">&nbsp;</td>
                            <?php elseif (in_array($i, [9])): ?>
                                <td class="active text-center"><i class="fa fa-star-o"></i></td>
                            <?php else: ?>
                                <td>&nbsp;</td>
                            <?php endif; ?>
                        <?php endfor; ?>
                    </tr>
                    <tr>
                        <td>John Кирилов</td>
                        <?php for($i=1; $i<32; $i++): ?>
                            <?php if (in_array($i, [7, 8])): ?>
                                <td class="active text-center">&nbsp;</td>
                            <?php elseif (in_array($i, [9])): ?>
                                <td class="active text-center"><i class="fa fa-star-o"></i></td>
                            <?php else: ?>
                                <td>&nbsp;</td>
                            <?php endif; ?>
                        <?php endfor; ?>
                    </tr>
                    </tbody>
                </table>

                <div class="row">
                    <div class="col-md-12 panel-padding">
                        <div style="float:left; margin-right: 20px;">
                            <div style="width:20px; height: 20px; float:left;background-color: #f5f5f5; margin-right: 10px; border:1px #e4e4e4 solid;">&nbsp;</div>
                            Выходной
                        </div>
                        <div style="float:left; margin-right: 20px;">
                            <div style="width:20px; height: 20px; float:left;background-color: #f5f5f5; margin-right: 10px; border:1px #e4e4e4 solid;">&nbsp;<i class="fa fa-star-o"></i></div>
                            Гос. праздник
                        </div>
                        <div style="float:left; margin-right: 20px;">
                            <div style="width:20px; height: 20px; float:left;background-color: #d9edf7; margin-right: 10px; border:1px #e4e4e4 solid;">&nbsp;О</div>
                            Отпуск
                        </div>
                        <div style="float:left; margin-right: 20px;">
                            <div style="width:20px; height: 20px; float:left;background-color: #fcf8e3; margin-right: 10px; border:1px #e4e4e4 solid;">&nbsp;Б</div>
                            Больничный
                        </div>
                        <div style="float:left; margin-right: 20px;">
                            <div style="width:20px; height: 20px; float:left;background-color: #dff0d8; margin-right: 10px; border:1px #e4e4e4 solid;">&nbsp;У</div>
                            Учебный
                        </div>
                        <div style="float:left; margin-right: 20px;">
                            <div style="width:20px; height: 20px; float:left;background-color: #f2dede; margin-right: 10px; border:1px #e4e4e4 solid;">&nbsp;П</div>
                            За свой счет
                        </div>
                    </div>
                </div>

                <ul class="pagination">
                    <li><a href="#">«</a></li>
                    <li><a href="#">2013 Dec</a></li>
                    <li><a href="#">2014 Jan</a></li>
                    <li class="active"><a href="#">2014 Feb <span class="sr-only">(current)</span></a></li>
                    <li><a href="#">2014 Mar</a></li>
                    <li><a href="#">2014 Apr</a></li>
                    <li><a href="#">»</a></li>
                </ul>
            </div>
        </div>
        <!-- End .panel -->
    </div>


</div>