<div class="page-header">
    <div class="row">
        <h1 class="col-sm-4 text-center text-left-sm col-xs-12">
            <i class="fa fa-calendar page-header-icon"></i>&nbsp;&nbsp;<a href="/employees">Timesheet</a>
        </h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <!-- col-lg-4 start here -->
        <div class="panel panel-default plain">
            <!-- Start .panel -->
            <div class="panel-heading">
                <h4 class="panel-title">2014 February</h4>
            </div>
            <div class="panel-body">
                <table class="table table-hover table-bordered">
                    <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <?php for($i=1; $i<32; $i++): ?>
                            <th><?= $i; ?></th>
                        <?php endfor; ?>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Mark</td>
                        <?php for($i=1; $i<32; $i++): ?>
                            <th>&nbsp;</th>
                        <?php endfor; ?>
                    </tr>
                    <tr>
                        <td>Jacob</td>
                        <?php for($i=1; $i<32; $i++): ?>
                            <th>&nbsp;</th>
                        <?php endfor; ?>
                    </tr>
                    <tr>
                        <td>Larry</td>
                        <?php for($i=1; $i<32; $i++): ?>
                            <th>&nbsp;</th>
                        <?php endfor; ?>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- End .panel -->
    </div>

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <!-- col-lg-4 start here -->
        <div class="panel panel-default plain">
            <!-- Start .panel -->
            <div class="panel-heading">
                <h4 class="panel-title">2014 March</h4>
            </div>
            <div class="panel-body">
                <table class="table table-hover table-bordered">
                    <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <?php for($i=1; $i<31; $i++): ?>
                            <th><?= $i; ?></th>
                        <?php endfor; ?>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Mark</td>
                        <?php for($i=1; $i<31; $i++): ?>
                            <th>&nbsp;</th>
                        <?php endfor; ?>
                    </tr>
                    <tr>
                        <td>Jacob</td>
                        <?php for($i=1; $i<31; $i++): ?>
                            <th>&nbsp;</th>
                        <?php endfor; ?>
                    </tr>
                    <tr>
                        <td>Larry</td>
                        <?php for($i=1; $i<31; $i++): ?>
                            <th>&nbsp;</th>
                        <?php endfor; ?>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- End .panel -->
    </div>

</div>