<div class="page-header">
    <div class="row">
        <h1 class="col-sm-4 text-center text-left-sm col-xs-12">
            <i class="fa fa-calendar page-header-icon"></i>&nbsp;&nbsp;<a href="/employees">Timesheet</a>&nbsp;&nbsp;<i class="fa fa-angle-right page-header-icon"></i>&nbsp;&nbsp;Add employee
        </h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
        <!-- col-lg-4 start here -->
        <div class="panel panel-default plain">
            <!-- Start .panel -->
            <div class="panel-heading">
                <h4 class="panel-title">Personal info</h4>
            </div>
            <div class="panel-body">
                <form role="form" class="form-vertical">
                    <div class="form-group">
                        <label class="control-label">Фамилия</label>
                        <input type="text" value="SuggeElson" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Имя</label>
                        <input type="text" value="Jonh Doe" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Отчество</label>
                        <input type="email" value="suggeelson@suggeelson.com" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Дата рождения</label>
                        <input type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Телефоны</label>
                        <input type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Данные паспорта</label>
                        <textarea rows="3" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <label class="control-label">ИПН</label>
                        <input type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Адрес факт</label>
                        <textarea rows="3" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Адрес прописки</label>
                        <textarea rows="3" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Контактные лица</label>
                        <textarea rows="3" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary" type="submit">Save</button>
                    </div>
                    <!-- End .form-group  -->
                </form>
            </div>
        </div>
        <!-- End .panel -->
    </div>

    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
        <!-- col-lg-4 start here -->
        <div class="panel panel-default plain">
            <!-- Start .panel -->
            <div class="panel-heading">
                <h4 class="panel-title">Photo</h4>
            </div>
            <div class="panel-body">
                <form role="form" class="form-vertical">
                    <div class="form-group">
                        <label class="control-label">Дата приема на работу</label>
                        <input type="text" value="Jonh Doe" class="form-control">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary" type="submit">Save</button>
                    </div>
                    <!-- End .form-group  -->
                </form>
            </div>
        </div>
        <!-- End .panel -->

        <div class="panel panel-default plain">
            <!-- Start .panel -->
            <div class="panel-heading">
                <h4 class="panel-title">Work info</h4>
            </div>
            <div class="panel-body">
                <form role="form" class="form-vertical">
                    <div class="form-group">
                        <label class="control-label">Должность</label>
                        <select class="form-control form-group-margin">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Статус</label>
                        <select class="form-control form-group-margin">
                            <option>На испытательном</option>
                            <option>Работает</option>
                            <option>Уволен</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Дата приема на работу</label>
                        <input type="text" value="Jonh Doe" class="form-control">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Дата увольнения</label>
                        <input type="email" value="suggeelson@suggeelson.com" class="form-control">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary" type="submit">Save</button>
                    </div>
                    <!-- End .form-group  -->
                </form>
            </div>
        </div>
    </div>

    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
        <!-- col-lg-4 start here -->
        <div class="panel panel-default plain">
            <!-- Start .panel -->
            <div class="panel-heading">
                <h4 class="panel-title">Social</h4>
            </div>
            <div class="panel-body">
                <form role="form" class="form-vertical">
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-skype"></i></span>
                            <input type="text" placeholder="Skype" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-envelope-o"></i></span>
                            <input type="text" placeholder="Personal e-mail" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-envelope-o"></i></span>
                            <input type="text" placeholder="Work e-mail" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-facebook-square"></i></span>
                            <input type="text" placeholder="Skype" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-vk"></i></span>
                            <input type="text" placeholder="Skype" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-linkedin"></i></span>
                            <input type="text" placeholder="Skype" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary" type="submit">Save</button>
                    </div>
                    <!-- End .form-group  -->
                </form>
            </div>
        </div>
        <!-- End .panel -->
    </div>

</div>